<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_TEST" Id="{c9df370d-c0ed-441f-b0c3-9ace7414a6e0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
	fbRunHOMSTest : FB_RunHOMS_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>